version: "3"
services:
  # algod-docker0:
  #   container_name: algod-docker0
  #   image: algorand/stable:latest
  #   ports:
  #     - '9001:8081'
  #   expose:
  #     - "8081"
  #   environment:
  #     - ALGORAND_DATA=/root/node/data
  #   volumes:
  #     - ./data:/root/node/data
  #   tty: true
  #   stdin_open: true
  algod-docker:
    container_name: algod-docker
    image: algod-docker
    ports:
      - "9001:8080"
    platform: linux/amd64
    environment:
      - ALGORAND_NETWORK=mainnet
    volumes:
      - ./data:/root/node/data
    tty: true
    stdin_open: true
